/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdbd0",
        "on-primary-container": "#006970",
        "surface-tint": "#00dbe9",
        "inverse-surface": "#e5e2e1",
        "on-secondary-fixed": "#3a0b00",
        "on-secondary-fixed-variant": "#852400",
        "on-tertiary-fixed-variant": "#5700c9",
        "background": "#131313",
        "secondary": "#ffb59e",
        "on-primary-fixed": "#002022",
        "outline": "#849495",
        "primary-fixed": "#7df4ff",
        "inverse-primary": "#006970",
        "on-error-container": "#ffdad6",
        "secondary-container": "#ff571a",
        "on-secondary-container": "#521300",
        "on-tertiary": "#3c0090",
        "surface-container": "#201f1f",
        "on-primary-fixed-variant": "#004f54",
        "error-container": "#93000a",
        "tertiary": "#faf3ff",
        "primary-fixed-dim": "#00dbe9",
        "on-error": "#690005",
        "primary": "#dbfcff",
        "surface-bright": "#3a3939",
        "tertiary-container": "#e1d2ff",
        "on-primary": "#00363a",
        "tertiary-fixed-dim": "#d1bcff",
        "on-secondary": "#5e1700",
        "surface-dim": "#131313",
        "surface-variant": "#353534",
        "on-background": "#e5e2e1",
        "primary-container": "#00f0ff",
        "surface": "#131313",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#e9ddff",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#7213ff",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#23005b",
        "secondary-fixed-dim": "#ffb59e",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "outline-variant": "#3b494b",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#b9cacb"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "mono": ["Space Grotesk"],
      },
    },
  },
  plugins: [],
}
