"""sync_schema

Revision ID: 6aec17288bcb
Revises: fdfa2269b6e6
Create Date: 2026-05-20 19:20:27.898943
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aec17288bcb'
down_revision: Union[str, None] = 'fdfa2269b6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_sessions', sa.Column('output_video_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_sessions', 'output_video_path')
    # ### end Alembic commands ###
