"""add full_name to users

Revision ID: fdfa2269b6e6
Revises: 001
Create Date: 2026-05-05 17:18:38.499997
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfa2269b6e6'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if table already exists (Legacy support for create_all)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'users' not in tables:
        op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=64), nullable=False),
            sa.Column('full_name', sa.String(length=255), nullable=True),
            sa.Column('email', sa.String(length=255), nullable=True),
            sa.Column('hashed_password', sa.String(length=255), nullable=True),
            sa.Column('google_id', sa.String(length=255), nullable=True),
            sa.Column('avatar_url', sa.Text(), nullable=True),
            sa.Column('role', sa.String(length=32), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    else:
        # Table exists, just ensure full_name is there
        columns = [c['name'] for c in inspector.get_columns('users')]
        if 'full_name' not in columns:
            op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))

    # Ensure other indices are present
    existing_indexes = {idx['name'] for idx in inspector.get_indexes('cameras')}
    if 'ix_cameras_id' not in existing_indexes:
        op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    
    # ... and so on for other tables if needed, but the above is the critical part


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_id'), table_name='violations')
    op.drop_index(op.f('ix_violation_assets_id'), table_name='violation_assets')
    op.drop_index(op.f('ix_traffic_counts_id'), table_name='traffic_counts')
    op.drop_index(op.f('ix_processing_sessions_id'), table_name='processing_sessions')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
