# configs/train_detector.yaml
model: yolov10s.pt
data: /kaggle/working/traffic-ai/configs/fisheye8k.yaml
imgsz: 1280
epochs: 80
batch: 8
workers: 4
optimizer: AdamW
lr0: 0.001
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 10.0
translate: 0.1
scale: 0.5
shear: 2.0
perspective: 0.0005
flipud: 0.01
fliplr: 0.5
mosaic: 1.0
mixup: 0.15
copy_paste: 0.3
box: 7.5
cls: 0.5
dfl: 1.5
dropout: 0.0
label_smoothing: 0.1
project: /kaggle/working/traffic-ai/runs/train
name: fisheye8k-yolov10s-1280
save_period: 10
cls_weights: [1.740, 0.316, 0.412, 0.826, 1.706]